name: Deploy ConversaCraft

on: 
  push: 
    branches:
      - master

jobs: 
  build: 
    runs-on: ubuntu-latest
    steps: 
      - name: Checkout Source
        uses: actions/checkout@v4
      - name: Login to docker hub
        run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
      - name: Build Docker Image
        run: docker build -t mienpham04/conversa_craft .
      - name: Publish Image to docker hub
        run: docker push mienpham04/conversa_craft:latest

  deploy: 
    needs: build
    runs-on: self-hosted
    steps: 
      - name: Pull image from docker hub
        run: docker pull mienpham04/conversa_craft:latest
      - name: Run Docker Container
        run: docker run -d -p 5000:5000 --name conversa-craft-container -e MONGO_PASSWORD='${{ secrets.MONGO_PASSWORD }}' mienpham04/conversa_craft


